[project]
name = "sentinellm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "openai>=2.8.1",
    "pandas>=2.3.3",
    "pyarrow>=22.0.0",
    "ray[serve]>=2.52.0",
    "uvloop>=0.22.1",
    "vllm>=0.11.2",
]
